name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: git describe tags
        run: git -C . describe --tags

      - name: git describe tags match
        run: git -C . describe --tags --match "v[0-9]*"

      - name: git describe tags match abbrev
        run: git -C . describe --tags --match "v[0-9]*" --abbrev=0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: actions-goveralls
        uses: shogo82148/actions-goveralls@v1.6.0

      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0
