name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.16"
          - "1.23"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tags
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -coverprofile=coverage.txt ./...

      - name: actions-goveralls
        uses: shogo82148/actions-goveralls@v1.6.0
        with:
          path-to-profile: coverage.txt

      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0
