name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: actions-goveralls
      # You may pin to the exact commit or the version.
      # uses: shogo82148/actions-goveralls@31ee804b8576ae49f6dc3caa22591bc5080e7920
      uses: shogo82148/actions-goveralls@v1.6.0
      #with:
        # Coveralls uses this token to verify the posted coverage data on the repo and create a new check based on the results.
        #github-token: # default is ${{ github.token }}
        # a path to your cover profile.
        #path-to-profile: # optional, default is 
        # Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.
        #parallel: # optional
        # Set to true for the last action when using "parallel: true".
        #parallel-finished: # optional
        # job number (DEPRECATED)
        #job-number: # optional, default is ${{ strategy.job-index }}
        # Job flag name, e.g. "Unit", "Functional", or "Integration". Will be shown in the Coveralls UI.
        #flag-name: # optional, default is ${{ strategy.job-index }}
        # working directory
        #working-directory: # optional, default is .
        # Comma separated files to ignore
        #ignore: # optional, default is 
        # Shallow coveralls internal server errors
        #shallow: # optional
